#!/usr/bin/env bash
# Script to display a list of currently running processes.
# It shows all processes, for all users, including those
# which might not have a TTY.

# Use the "ps" command with options to display the process list.
ps -auxf
