#!/usr/bin/env bash
# Kills the 4-to_infinity_and_beyond process.

if pkill -f 4-to_infinity_and_beyond; then
  echo "Process 4-to_infinity_and_beyond killed."
else
  echo "Process 4-to_infinity_and_beyond not found."
fi
