#!/usr/bin/env bash
# Displays "To infinity and beyond" indefinitely
#+ with a sleep of 2 seconds between each iteration.
# Displays "I am invincible!!!" in response to a SIGTERM signal.

# Define the SIGTERM signal handler to display "I am invincible!!!"
trap 'echo "I am invincible!!!"' SIGTERM

while true
do
  echo "To infinity and beyond"
  sleep 2
done
