#!/usr/bin/env bash
# Bash script that displays numbers from 1 to 100 and applies the FizzBuzz rule.

# Requirements:
# - Display numbers from 1 to 100 in a list format.
# - If a number is a multiple of both 3 and 5, display "FizzBuzz."
# - If a number is a multiple of 3 (but not 5), display "Fizz."
# - If a number is a multiple of 5 (but not 3), display "Buzz."
# - Otherwise, display the number itself.

for ((i=1; i<=100; i++)); do
    if [[ $((i % 3)) -eq 0 && $((i % 5)) -eq 0 ]]; then
        echo "FizzBuzz"
    elif [[ $((i % 3)) -eq 0 && $((i % 5)) -ne 0 ]]; then
        echo "Fizz"
    elif [[ $((i % 5)) -eq 0 && $((i % 3)) -ne 0 ]]; then
        echo "Buzz"
    else
        echo "$i"
    fi
done
