#!/usr/bin/env bash
# Display "Best School" 10 times.
# On the 9th iteration, display "Best School" and then "Hi" on a new line.
# Implement this using a while loop and an if statement.

i=0
while [[ "$i" -lt 10 ]]; do
    if [[ "$i" -eq 9 ]]; then
        echo "Hi"
    fi
    echo "Best School"
    (( i++ ))
done
