#!/usr/bin/env bash
# Loops from 1 to 10 and displays messages based on loop iteration.
# - Displays "bad luck" for the 4th loop iteration.
# - Displays "good luck" for the 8th loop iteration.
# - Displays "Best School" for all other iterations.
# This script uses a while loop and conditional statements (if, elif, and else).

i=0
while [[ "$i" -lt 10 ]]; do
    if [[ "$i" -eq 3 ]]; then
        echo "bad luck"
    elif [[ "$i" -eq 7 ]]; then
        echo "good luck"
    else
        echo "Best School"
    fi
    (( i++ ))
done
