#!/usr/bin/env bash
# Display numbers from 1 to 20 and provide specific messages for certain iterations:
# - For the 4th iteration, display "4" and then "bad luck from China."
# - For the 9th iteration, display "9" and then "bad luck from Japan."
# - For the 17th iteration, display "17" and then "bad luck from Italy."
# For all other iterations, just display the number.
#
# This script uses a while loop and a case statement for conditional branching.

i=1
while [[ "$i" -lt 21 ]]; do
    case $i in 
        4 )  echo -e "$i\nbad luck from China"
            ;;
        9 ) echo -e "$i\nbad luck from Japan"
            ;;
        17 ) echo -e "$i\nbad luck from Italy"
            ;;
        * ) echo "$i"
    esac
    (( i++ ))
done
