#!/usr/bin/env bash
# Bash script that provides information about the "school" file.

# Requirements:
# - Use if and else (case is forbidden).
# - Check if the file exists and print:
#   - If the file exists: "school file exists."
#   - If the file does not exist: "school file does not exist."
# - If the file exists, print:
#   - If the file is empty: "school file is empty."
#   - If the file is not empty: "school file is not empty."
#   - If the file is a regular file: "school is a regular file."
#   - If the file is not a regular file: (nothing).

file="school"

if [ -e "$file" ]; then
    echo "school file exists"
    if [ ! -s "$file" ]; then 
        echo "school file is empty"
    else
        echo "school file is not empty"
    fi
    if [ -f "$file" ]; then
        echo "school is a regular file"
    else
        echo -n ""
    fi
else 
    echo "school file does not exist"
fi
